server:
  port: 8082

spring:
  application:
    name: productservice

  # datasource:
  #   url: jdbc:mysql://mysql:3306/product # use to connect mysql from container to mysql pod
  #   username: root
  #   password: password
  #   driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
