apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: orderservice
          image: adeshprime17/orderservice252:0.0.1
          ports:
            - containerPort: 8084
          env:   #setting here to we can change the thing from here
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/orderdatabase
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: password

---
#service for order
apiVersion: v1
kind: Service
metadata:
  name: orderservice-service
spec:
  selector:
    app: orderservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
  type: LoadBalancer
