apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          image: adeshprime17/paymentservice25:0.0.1
          ports:
            - containerPort: 8085
          env:   #setting here to we can change the thing from here
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/paymentdb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: password

---
#service for order
apiVersion: v1
kind: Service
metadata:
  name: paymentservice-service
spec:
  selector:
    app: paymentservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  type: ClusterIP
