server:
  port: 8081

spring:
  application:
    name: userservice

  datasource:
    url: jdbc:mysql://mysql:3306/user # use to connect mysql from container to your local mysql
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
