server:
  port: 8086

spring:
  application:
    name: deliveryservice

#  datasource:
#     url: jdbc:mysql://localhost:3306/deliverydb
#     username: root
#     password: password
#     driver-class-name: com.mysql.cj.jdbc.Driver  #This is the JDBC driver class provided by MySQL Connector/J (the official MySQL driver for Java).

  jpa:
    hibernate:
      ddl-auto: update   # change to none if schema is already created
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


#using this for changing the status of the order
order:
  service:
    url: http://orderservice-service/api/order/updateStatus

#feign:
#  client:
#    config:
#      payment-service:
#        url: http://paymentservice-service
