pipeline {
    agent any

    environment {
        IMAGE_NAME = 'adeshprime17/userservice25'
        IMAGE_TAG = '0.0.1'
        KUBECONFIG = 'C:\\ProgramData\\Jenkins\\.kube\\config'  // Path for Jenkins to access kubeconfig
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out source code...'
                checkout scm
            }
        }

        stage('Build with Maven') {
            steps {
                echo 'Building the project using Maven...'
                dir('userservice') {
                    bat 'mvnw.cmd clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                bat "docker build -t %IMAGE_NAME%:%IMAGE_TAG% ./userservice"
            }
        }

        stage('Push to Docker Hub') {
            steps {
                echo 'Pushing Docker image to Docker Hub...'
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                    bat '''
                        echo Logging into Docker Hub...
                        docker login -u %DOCKER_USERNAME% -p %DOCKER_PASSWORD%
                        docker push %IMAGE_NAME%:%IMAGE_TAG%
                    '''
                }
            }
        }

        stage('Start Minikube') {
            steps {
                echo 'Starting Minikube...'
                bat 'minikube start'
                bat 'kubectl config use-context minikube'
            }
        }

    //     stage('Deploy to Kubernetes') {
    //         steps {
    //             echo 'Deploying to Kubernetes...'
    //             bat 'kubectl apply -f ./k8s/userservice-deployment.yaml'
    //             bat 'kubectl apply -f ./k8s/userservice-service.yaml'
    //         }
    //     }
     }

    post {
        always {
            echo 'Pipeline finished.'
        }
    }
}
